### ISSUE TITLE
Keyboard shortcut to push currently active file to netsuite

### ISSUE THREAD

**Issue by smith288** [netsuite-upload-org/netsuite-upload#11]
I think it would be a nice addition to push the current active document to netsuite by hitting a shortcut.  As it stands right now, the plugin doesn't recognize the active document.  Im required to right click on the file in the browser to push it.

**Comment by silverl** [comment]
This is now resolved with v1.0.0. Please beta-test it here: https://github.com/netsuite-upload-org/netsuite-upload/releases/tag/v1.0.0

See the README.md for instructions how to add the keybinding you desire.

**Comment by smith288** [comment]
SO MUCH BETTER! Thanks!
