### ISSUE TITLE
Temp Path Mac

### ISSUE THREAD

**Issue by adman2002** [netsuite-upload-org/netsuite-upload#14]
Trying to get the compare function to work on a Mac, but it is not recognizing the file path. It looks like the plugin is inserting a backslash.

Settings:
"netSuiteUpload.tempFolder": "/Users/aparker/Downloads"

Error:
Unable to open 'Local <--> NetSuite': File not found (file:///Users/aparker/Downloads\/KESEB_CS_Transaction.preview.js).

**Comment by silverl** [comment]
Path looks ok to my eyes. Are you 100% sure that folder exists? And that your user has write access to it?

I mean, it should, because I think that's the default path to your user Downloads folder on a mac.

Maybe try using ~/Downloads instead?

Or try pointing it to /tmp

**Comment by adman2002** [comment]
Yes, I verified access and tried both the relative path and /tmp folder. I could be wrong, but it looks like a forward slash being inserted and maybe that is the issue.

Unable to open 'Local <--> NetSuite': File not found (file:///tmp\/KESEB_CS_Transaction.preview.js).

Adam Parker, MCSA
Member, Director of Technology

Kraft Enterprise Systems, LLC
10 Cadillac Drive, Suite 380
Brentwood, TN  37027
(615) 665-2545x111
aparker@kraftenterprise.com<mailto:aparker@kraftenterprise.com>

Sign up for timely news updates from KraftCPAs here<http://www.kraftcpas.com/Newsletter_Email_List.php>!

**Comment by silverl** [comment]
I think you mean "backslash". There was no backslash in your original post, so it looked "correct". 

FYI your full sig came along with your email reply.

One other thing to check -- is your VS Code project folder root in the same place as the Netsuite root? By this I mean the extension might not be able to align the paths between local VS code folder root and Netsuite Suitescripts root.

**Comment by adman2002** [comment]
Correct, backslash. Sorry still getting used to the Mac. I'll keep poking around. Thanks.

**Comment by silverl** [comment]
The solution stopped working for me some months ago. Probably a change in Netsuite's API authentication model. The developer appears to have abandoned this project. No new commits in over a year, and not responding to issues.

**Comment by JosueIsaiSmg** [comment]
O this is so sad, Is there another alternative for this extension in a different editor?

**Comment by silverl** [comment]
There's the officially sanctioned one for Eclipse, but I can't bring myself to use it. That's how I landed here.

A lot of people have forked this project (I probably have myself):
https://github.com/tvrdytom/netsuite-upload/network/members

Maybe someone out there got it working. You'd have to look at them all to find one though.

I barely use this extension anymore myself, so I've resorted to just manually changing the scripts I do need to touch.

**Comment by silverl** [comment]
@JosueIsaiSmg if you're willing to install my fork, the mac temp folder issue should be fixed there: https://github.com/silverl/netsuite-upload

**Comment by tvrdytom** [comment]
Hey guys. Sorry for not responding for quite a long time. I have left the company that used NetSuite 2 years ago and it looks like the guy I asked to continue the development haven't touched it at all. I have no access to NetSuite any more so cannot continue with the development. If there is anybody who's willing to continue, just give me a note please and I can give you an access to keep this up to date.
Thanks

**Comment by silverl** [comment]
@tvrdytom Thanks for checking in. I appreciate you offering me commit access to this repository. I do a spurt of NetSuite coding for work every few months, and I've found your tool very useful.

What is the VSIX build and publish process?

**Comment by tvrdytom** [comment]
Hey @silverl, I think you just need to be set as a contributor of the extension to be able to update it in the VS marketplace, right?. If so, I just need some your MS account email and I'll give you the access rights. You can send me your email vie email message to tvrdytom@gmail.com or just put it here, if you don't mind. Thanks :)

**Comment by silverl** [comment]
I sent it privately.

**Comment by silverl** [comment]
This issue is now resolved in v1.0.0 https://github.com/netsuite-upload-org/netsuite-upload/releases/tag/v1.0.0 

I'm not confident enough yet to release this to the VS Code marketplace without some beta testing first. @adman2002  would you care to replace your Marketplace extension with the 1.0.0 release and try this out?

**Comment by silverl** [comment]
I've un-published the original extension and re-published it under my own credentials. Please uninstall old and install new. The name is the same, `netsuite-upload`.

https://marketplace.visualstudio.com/items?itemName=nsupload-org.netsuite-upload
