### ISSUE TITLE
Request for clearer setup documentation

### ISSUE THREAD

**Issue by srhcrete** [netsuite-upload-org/netsuite-upload#15]
I'm trying to follow the setup instructions, but haven't gotten it to work. I've tried different role id's, moving the file location to the root of the suitscript folder and re-deploying it from there, I've tried different account id's and different formats for the account id, the restlet URL as both the internal and external URL, used both windows and mac computer with different temp folder paths, we know that it was authenticating at one point because we received a success message relating to the folder being pulled from netsuite, however no folders or files were actually pulled down to local. More detailed setup instructions or error messages would be really helpful.

**Comment by silverl** [comment]
I've done a lot of work on the README.md. Please have a look.

**Comment by philipdenys** [comment]
It's a bit confusing to me, did anyone make a video tutorial about setting it up?
