### ISSUE TITLE
Pull,Push,Delete,Compare, don't work Windows/Mac (v1.0.3)

### ISSUE THREAD

**Issue by JosueIsaiSmg** [netsuite-upload-org/netsuite-upload#19]

**Comment by silverl** [comment]
Have you updated the RESTlet?

Are there errors shown in the IDE? Can you share?

How about errors shown in the Help...Toggle Developer Tools console?

**Comment by JosueIsaiSmg** [comment]
![image](https://user-images.githubusercontent.com/22876037/52495496-72a4c300-2b96-11e9-9c8f-cd264490ad65.png)
Yes I've updated the RESTlet, in the IDE there are no notifications showing

**Comment by silverl** [comment]
Found, fixed. v1.1.2.

**Comment by silverl** [comment]
Install from Marketplace, by the way. https://marketplace.visualstudio.com/items?itemName=nsupload-org.netsuite-upload

**Comment by silverl** [comment]
Grr, still having an issue. Troubleshooting.

**Comment by silverl** [comment]
Nope, I did fix it.  Just needed to reload VS Code. Should be good to go.
