### ISSUE TITLE
NsUpload - Keep folder structure

### ISSUE THREAD

**Issue by Godrules500** [netsuite-upload-org/netsuite-upload#2]
I've been using Webstorm's NetSuite's plugin and it works great. However, I love VSCode much more. Do you know if NSUpload will ever work without a RESTlet and with keeping the folder structure?

**Comment by lakewoodDev** [comment]
Is there a way to set keyboard shortcuts to upload a file?

**Comment by JonnyBoy333** [comment]
What do you mean by 'keeping the folder structure' exactly? Right now the extension assumes everything is going into the SuiteScript fold, though whatever sub folders you create in your project should get created automatically in NetSuite. Are you talking about being able to choose a different root folder in NetSuite like you can do in the Webstorm plugin?

**Comment by silverl** [comment]
The plugin cannot work without a RESTlet to my knowledge. There must be code on the server to manipulate the File Cabinet contents.

The latest build supports changing the base directory in the NetSuite file cabinet, so you can push/pull files to other folders than SuiteScripts.

Note that  your Role might require additional permissions for other kinds of folders. For example, SuiteBundles requires a specific permission.
