### ISSUE TITLE
Errro to push file into Netsuite.

### ISSUE THREAD

**Issue by uditrajput** [netsuite-upload-org/netsuite-upload#26]
Kindly help me. I am facing issue to push the file into netsuite. Other operations are working fine.
VSCode Details :
Version: 1.33.1
Date: 2019-04-11T08:20:22.771Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 4.15.0-47-generic

for more information find the below stack trace:
ERROR uploading file. | Unknown Error: | HTTP Status: undefined | HTTP Error: Unexpected token ' in JSON at position 186 | Local Stack: | SyntaxError: Unexpected token ' in JSON at position 186 at JSON.parse (<anonymous>) at IncomingMessage.module.exports.res.on (/home/udit/.vscode/extensions/nsupload-org.netsuite-upload-1.1.2/node_modules/superagent/lib/node/parsers/json.js:11:35) at Stream.emit (events.js:182:13) at Stream.EventEmitter.emit (domain.js:442:20) at Unzip.exports.unzip.unzip.on (/home/udit/.vscode/extensions/nsupload-org.netsuite-upload-1.1.2/node_modules/superagent/lib/node/unzip.js:55:12) at Unzip.emit (events.js:187:15) at Unzip.EventEmitter.emit (domain.js:442:20) at endReadableNT (_stream_readable.js:1090:12) at process._tickCallback (internal/process/next_tick.js:63:19) | Use Help…Toggle Developer Tools and choose the Console tab for a better formatted error message.

**Comment by silverl** [comment]
Based on the exception contents, it looks to me like there's an unexpected character in the file that you're trying to push to NetSuite. The extension uses a node library called `superagent` to make HTTP calls to NetSuite. The json parser embedded in `superagent` is choking on something in the file. 

Are you able to push other files?

Are you able to share the contents of the file that will not push?

**Comment by uditrajput** [comment]
Hi Silverl,
I am using a simple UserEventScript name test.js
/**
 *@NApiVersion 2.x
 *@NScriptType UserEventScript
 */
define([], function() {

    function beforeLoad(context) {
        
    }

    function beforeSubmit(context) {
        
    }

    function afterSubmit(context) {
        
    }

    return {
        beforeLoad: beforeLoad,
        beforeSubmit: beforeSubmit,
        afterSubmit: afterSubmit
    }
});

i am not able to push other file also.
after manually upload a file in netsuite 'Compare file with netsuit' and delete operation working fine but i am getting error when i push the file in netsuite.
i am using Node version v10.15.3 on my machine.

**Comment by silverl** [comment]
Visually, I don't see anything wrong with your code. Perhaps there is something wrong with the file encoding. Are you working with ASCII or UTF-8 text files? Or is it some other kind of encoding?

This seems like a strange problem I haven't seen before.

**Comment by uditrajput** [comment]
I am using default encoding in VSCode it's UTF-8 and now i have created a different file with encoding ASCII and try to upload it in netsuite got the same error.

**Comment by uditrajput** [comment]
I have setup VSCode on windows environment and try to push the file in netsuite. but got the same error.
VSCode Infromation : 
Version: 1.33.1 (user setup)
Commit: 51b0b28134d51361cf996d2f0a1c698247aeabd8
Date: 2019-04-11T08:27:14.102Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 6.1.7601 

Extension Information :
Name: NetSuite Upload
Id: nsupload-org.netsuite-upload
Description: Upload and download NetSuite SuiteScript files and folders.
Version: 1.1.2
Publisher: nsupload-org
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=nsupload-org.netsuite-upload

**Comment by uditrajput** [comment]
Thank you Silverl!
I was facing this issue lack of permission to the user role.
I have applied permission to the role and it's working.
Setup>users/Roles>Manage Roles> "Choose Role you have applied" 
Edit>Permission>setup>**_'Allow js/HTML Uploads'_**

**Comment by uditrajput** [comment]
I am facing another issue.
If you have a folder in netsuite by the name **Restlet** and you have a folder name **restlet** in VSCode i mean case sensitive. File pushed successfully but when i am trying to delete that file it is not deleted because path does not exist.
Error log : 
{
  "type": "error.SuiteScriptError",
  "name": "RCRD_DSNT_EXIST",
  "message": "That record does not exist. path: SuiteScripts/restlet/showmessage2.js",
  "stack": [
    "load(N/file)",
    "deleteFile(/SuiteScripts/vscodeExtensionRestlet.js:352)",
    "deleteFunc(/SuiteScripts/vscodeExtensionRestlet.js:397)"
  ],
  "cause": {
    "type": "internal error",
    "code": "RCRD_DSNT_EXIST",
    "details": "That record does not exist. path: SuiteScripts/restlet/showmessage2.js",
    "userEvent": null,
    "stackTrace": [
      "load(N/file)",
      "deleteFile(/SuiteScripts/vscodeExtensionRestlet.js:352)",
      "deleteFunc(/SuiteScripts/vscodeExtensionRestlet.js:397)"
    ],
    "notifyOff": false
  },
  "id": "",
  "notifyOff": false,
  "userFacing": false
}
Kindly fix this issue.

**Comment by silverl** [comment]
Path names are (I would expect) case-sensitive. It is probably an unintended consequence that it was able to push in the first place. I didn't write that code myself.

How did you arrive at having a difference in case between the client and server?

Can you just adjust one or the other? I'd modify the client code as you might break dependencies in Netsuite if you change the casing of the folders there.

**Comment by uditrajput** [comment]
Before using _NetSuite Upload extension_. I have manually created a folder name Restlet in netsuite few days ago.
I have google about netsuite upload file and found the VSCode extension. I have setup VSCode and at random make a folder restlet.

NetSuite Upload extension save a lot of development time of developers.
Thank you for your time and response.

**Comment by silverl** [comment]
You're welcome.
