### ISSUE TITLE
Pulled Folder once - now won't pull again

### ISSUE THREAD

**Issue by jjmartin** [netsuite-upload-org/netsuite-upload#27]
I was trying to get the script to work with a token that had the minimum privileges and during the process i switched to a token that had full admin privileges and the folder successfully pulled down.

I was trying to pull again after figuring out the permissions issues (you can't have only web service checked)  and I get an error in VS CODE: You might need to update the vscodeExtensionRestlet.js RESTlet in NetSuite to the latest version. | Use Help…Toggle Developer Tools and choose the Console tab for a better formatted error message.

But I was able to connect through postman and do the call : type=directory&name=SuiteScripts
and get a successful answer.

The extension won't work with either configured tokens i have

**Comment by silverl** [comment]
Hi, @jjmartin 

Are the minimal permissions documented in the README incorrect? Do I need to update them?

I see that error message (you might need to update the restlet) often when there are general permission errors. It's something that needs to get fixed. But for now, know that it usually means there's some other problem calling the RESTlet.

Are you seeing any errors in the NetSuite logs on the Script Deployment record?

Are you seeing additional messages in the VS Code Developer Tools?

Most important: Is your VS Code opening the folder that equates to the SuiteScripts folder in NetSuite? If you've opened VS Code on a folder above or below that, it won't work (without extra settings).

**Comment by jjmartin** [comment]
I don't receive a suitescript error when i activate the command in VSCode.  ( I do see some trying to make calls through postman where i didn't get the search filter right)

The main issue i had initially was that i had selected 
![image](https://user-images.githubusercontent.com/607183/56618562-977ed300-65e8-11e9-8b92-12026d20073e.png)
WEB SERVIVCES ONLY ROLE  
so don't do that, but i'm not sure its worth saying in the readme.

Fresh Eyes make all the difference - some how i had corrupted my settings, so the realm was all wrong (accidently pasted a key at the end of it) and somehow lost the URL of Restlet.   (which was blank)

it might be worth having a specific error if that URL setting doesn't have a value
