### ISSUE TITLE
Error uploading File

### ISSUE THREAD

**Issue by jjmartin** [netsuite-upload-org/netsuite-upload#29]
When i start with an empty project and pull folder, then try to push one of the files back up, I get the following error:

`ERROR uploading file. | Unknown Error: | HTTP Status: undefined | HTTP Error: Unexpected token ' in JSON at position 186 | Local Stack: | SyntaxError: Unexpected token ' in JSON at position 186 at JSON.parse (<anonymous>) at IncomingMessage.module.exports.res.on (C:\Users\jmartin\.vscode\extensions\nsupload-org.netsuite-upload-1.1.2\node_modules\superagent\lib\node\parsers\json.js:11:35) at Stream.emit (events.js:182:13) at Unzip.exports.unzip.unzip.on (C:\Users\jmartin\.vscode\extensions\nsupload-org.netsuite-upload-1.1.2\node_modules\superagent\lib\node\unzip.js:55:12) at Unzip.emit (events.js:187:15) at endReadableNT (_stream_readable.js:1090:12) at process._tickCallback (internal/process/next_tick.js:63:19) | Use Help…Toggle Developer Tools and choose the Console tab for a better formatted error message.`

**Comment by jjmartin** [comment]
Ok this was a permission issue:  these are the current permissions i have for the "Script Management" role i set up:
![image](https://user-images.githubusercontent.com/607183/57531863-16218300-7300-11e9-9806-db7e563043ab.png)
![image](https://user-images.githubusercontent.com/607183/57531886-25a0cc00-7300-11e9-9c6b-0e4443daf409.png)
At this point i think the fix for this would be to add the 'Allow JS / HTML Uploads' as a required permission

**Comment by dmhliu** [comment]
just came upon this  issue, having not used the extension in years. confirm that adding the  'Allow JS / HTML Uploads'  permission to my role fixed it
