### ISSUE TITLE
Keyboard shorcut

### ISSUE THREAD

**Issue by mayerlench** [netsuite-upload-org/netsuite-upload#3]
Is there a way to set keyboard shortcut to upload the current viewed file?

**Comment by lakewoodDev** [comment]
@tvrdytom Is there a way to do this?

**Comment by silverl** [comment]
This is possible in the new release. It's mapped by default to Ctrl+n,Ctrl+u. Download is Ctrl+n,Ctrl+d.

See README for instructions on keybindings.

I've un-published the original extension and re-published it under my own credentials. Please uninstall old and install new. The name is the same, `netsuite-upload`.

https://marketplace.visualstudio.com/items?itemName=nsupload-org.netsuite-upload
