### ISSUE TITLE
Add Netsuite dependency command doesn't work properly

### ISSUE THREAD

**Issue by alejndr** [netsuite-upload-org/netsuite-upload#31]
When using the command to add any of the dependencies of netsuite, it only fill the function part and not the 'N/XXXX' in the define.

**Comment by silverl** [comment]
I think I've determined the cause is in `codeChangeHelper.js` `editCurrentDocument()` function. It's  due to the improper calling of the async function vscode.workspace.applyEdit twice in a row. Same bug probably as https://github.com/Microsoft/vscode/issues/48908

The second non-async invocation of applyEdit doesn't work, and it's that second invocation that attempts to insert the path in the define.

The original author of this extension didn't use any async features at all, making this a somewhat involved fix.

If anyone is very familiar with async and would like to submit a PR for this, it would be appreciated. I'm not sure when I'll be able to get to it.

**Comment by HolgerSchade** [comment]
Hello @silverl,

I took a bit of time and I figured out how to resolve this issue:

As the applyEdits function is asynchronous, you need to await the completion of the applyEdit before you issue a new applyEdit. Hence you have to start at the file **codeChangeHelper.js** and make the **function editCurrentDocument** asynchrounuous and await the calls to applyEdit:

```

async function editCurrentDocument(vsEditor, coords, content){
    var vsDocument = getDocument(vsEditor);
    var edit = setEditFactory(vsDocument._uri, coords, content);
    var didApply = false;
    didApply = await vscode.workspace.applyEdit(edit);
     return didApply;
}

```

as this function in turn is called by **updateDocument** you have to make this function also an async function:


```
async function updateDocument(editor, startLine, startChar, endLine, endChar, content) {
    var editorCoords = {
        start : {
            line: startLine,
            char: startChar
        },
        end : {
            line: endLine,
            char: endChar
        }
    }
    
    var didApply = false; 
	didApply = await editCurrentDocument(editor, editorCoords, content);
	return didApply;
}

```

and then finally you also  can easily change the **addDependency function in netSuiteBl.js**  to an async function allowing the called updateDocument functions to be awaited:

```
async function addDependency(editor, pathText, paramText) {
    let docContent = editor.document.getText();
    
	let coords = codeChangeHelper.getCoords(docContent);	
    let oldParamsString = docContent.substring(coords.depParam.range[0], coords.depParam.range[1]);
    let newParamsString = codeChangeHelper.getUpdatedFunctionParams(paramText, oldParamsString);

    let newPathArrayString = codeChangeHelper.getUpdatedDepPath(pathText,
        coords.depPath ? docContent.substring(coords.depPath.range[0], coords.depPath.range[1]) : null);
 
    if (coords.depPath) {
		await codeChangeHelper.updateDocument(editor, coords.depParam.start.row - 1, coords.depParam.start.col,
            coords.depParam.end.row - 1, coords.depParam.end.col, newParamsString);
			
        await codeChangeHelper.updateDocument(editor, coords.depPath.start.row - 1, coords.depPath.start.col,
            coords.depPath.end.row - 1, coords.depPath.end.col, newPathArrayString);

    } else { // Path array not defined
        await codeChangeHelper.updateDocument(editor, coords.depParam.start.row - 1, coords.depParam.start.col,
            coords.depParam.end.row - 1, coords.depParam.end.col, newPathArrayString + ', ' + newParamsString);
    }
	
	return true;
}

```

This did the trick for me.

Regards, 

Holger

**Comment by HolgerSchade** [comment]
@silverl - I will create a pull request for you to merge this for a next release

**Comment by silverl** [comment]
Excellent, thank you for your contribution!

**Comment by silverl** [comment]
Release 1.2.4 resolves this bug.
