### ISSUE TITLE
Pull folder from NetSuite on Mac

### ISSUE THREAD

**Issue by joshhidley** [netsuite-upload-org/netsuite-upload#7]
Steps to reproduce: 
- On a Mac
- Open the SuiteScript folder as the root in VS Code
- Right-click in the SUITESCRIPT sidebar and select Pull folder from NetSuite

What happens:
- Nothing changes in VS Code even after hitting the refresh button.
- Open the SuiteScript folder in finder and you will see the all the files at the same level as SuiteScript, but with the folder names embedded with *back* slashes.

What should happen:
- It shouldn't use back slashes for the path separators. 
- The files should be placed in the correct folders on the HD.
![screen shot 2017-08-29 at 11 02 43 am](https://user-images.githubusercontent.com/122256/29836287-a44160f4-8ca9-11e7-976c-9a2ebaf45b1f.png)

**Comment by m-salamon** [comment]
I still have this issue.

**Comment by joshhidley** [comment]
If you go to my fork of the repo here: [https://github.com/joshhidley/netsuite-upload/tree/platform-path-fix/build](https://github.com/joshhidley/netsuite-upload/tree/platform-path-fix), I implemented the fix.

If you don't want to build it, and just want the vsix file to install it, I put it here: [https://github.com/joshhidley/netsuite-upload/tree/platform-path-fix/build](https://github.com/joshhidley/netsuite-upload/tree/platform-path-fix/build). I'm not sure of the best way to down load it from there.

I make no claims about this. Use at your own risk.

**Comment by m-salamon** [comment]
Thanks so much it works great!

This is how I implemented @joshhidley vsix file.
1. Download the file vsix file from Github.
2. In VS Code open extensions
3. At the top right click the menu icon
4. select the option **Install from VSIX...**
5. find your vsix file in folders and select it
6. YOUR GOOD TO GO!!

**Comment by silverl** [comment]
This should be good to go in the 1.0.0 release. See releases tab of this project. 

Once I get some beta testing done, I'll release the update to the marketplace.
