### ISSUE TITLE
Error pushing file 

### ISSUE THREAD

**Issue by mayerlench** [netsuite-upload-org/netsuite-upload#8]
How to recreate my error: 
1. Create a clientscript template. Push the file to netsuite.

2. Delete the validateField function but still return the validateField from the define. 
This will result in Vscode saying it successfully uploaded the file but the file wont actually change in the file cabinet.

It seems that if theres a function in the return that does not have a function reference, the file will not upload but vscode will say it has. 

Please add error handling for this.

**Comment by kriss3** [comment]
Hi, 
I am not the owner of this project but I am very interested how this plugin will turn out.
To add few comments here. 
First, I was able to reproduce you issue. 
Also, are you getting similar issue when you try to compare your local fine and the server file?
I noticed, when I change the content of the function (only) I am able to successfully push the file and changes to NS.
I think the issue with function removal is related to the way SuiteScripts are checked before they r loaded to NS. If there is a syntax issue NS platform will not allow to upload (this is the behavior I get in Eclipse). 
I am trying to find module/function that will check file for any syntax issue and throw error.
I will post more if I find something useful.
Thanks
Kris
btw. I have not seen much activity on this plugin from the owner unfortunately. There r few pull requests waiting with some interesting updates.

**Comment by lakewoodDev** [comment]
I use this plugin alot and would definitely be interested in doing work on it to add some key features that can perfect it. 

The error i had above was and error that happens so often, especially with custom modules where you are constantly changing and or adding functions.

**Comment by silverl** [comment]
I've done a lot of work on error handling in the new version.

I've un-published the original extension and re-published it under my own credentials. Please uninstall old and install new. The name is the same, `netsuite-upload`.

https://marketplace.visualstudio.com/items?itemName=nsupload-org.netsuite-upload

I'll mark this closed and if you continue to have issues, please open a new issue.
